In [1]:
import json
import os
from collections import defaultdict

import pandas as pd

experiments = set()
restr_directories = ["original_logits", "main_logits", "root_logits"]

uas_pd_results = defaultdict(dict)
las_pd_results = defaultdict(dict)

data_dict = {}

results = defaultdict(dict)
for restr_dir in restr_directories:
    for filename in os.listdir(restr_dir):
        if "metrics" in filename and "old" not in filename:
            with open(f"{restr_dir}/{filename}", 'r', encoding='utf-8') as file:
                exp_name, restr_name = filename.replace("metrics_", "").replace(".jsonl", "").split("_42_")
                assert restr_dir in restr_name
                data = json.load(file)
                filename_prefix = filename.split(".")[0]
                if filename_prefix + "_uas" in data:
                    uas_pd_results[exp_name][restr_dir] = data[filename_prefix + "_uas"]
                if filename_prefix + "_las" in data:
                    las_pd_results[exp_name][restr_dir] = data[filename.split(".")[0] + "_las"]
                experiments.add(exp_name)
                data_dict[filename] = data

wrong_experiments =  {}#{"Qwen3_4B_en_ewt_grct_en_ewt_grct", "Qwen3_0_6B_en_ewt_grct_en_ewt_grct",
                #"Qwen3_8B_en_ewt_grct_en_ewt_grct", "Qwen3_8B_fr_gsd_fr_gsd", "Qwen3_0_6B_fr_gsd_fr_gsd"}
for exp in experiments:
  if exp not in wrong_experiments: # TODO
    print(exp)
    uas_pd_results[exp] = pd.DataFrame(uas_pd_results[exp])
    las_pd_results[exp] = pd.DataFrame(las_pd_results[exp])

Qwen3_8B_ru_syntagrus_grct_ru_syntagrus
Qwen3_8B_fi_ftb_grct_fi_ftb_grct
Qwen3_8B_zh_gsd_grct_zh_gsd_grct
Qwen3_8B_fr_gsd_grct_fr_gsd
Qwen3_8B_ja_gsd_grct_ja_gsd_grct
Qwen3_0_6B_en_ewt_grct_en_ewt_grct
Qwen3_4B_fr_gsd_grct_fr_gsd
Qwen3_0_6B_fr_gsd_grct_fr_gsd
Qwen3_0_6B_zh_gsd_grct_zh_gsd_grct
Qwen3_4B_en_ewt_grct_en_ewt_grct
Qwen3_4B_fi_ftb_grct_fi_ftb_grct
Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct
Qwen3_0_6B_ja_gsd_grct_ja_gsd_grct
Qwen3_0_6B_ru_syntagrus_grct_ru_syntagrus
Qwen3_4B_ja_gsd_grct_ja_gsd_grct
Qwen3_4B_zh_gsd_grct_zh_gsd_grct
Qwen3_8B_en_ewt_grct_en_ewt_grct
Qwen3_4B_ru_syntagrus_grct_ru_syntagrus

In [2]:
data_dict["metrics_Qwen3_0_6B_en_ewt_grct_en_ewt_grct_42_main_logits_0.jsonl"]["metrics_Qwen3_0_6B_en_ewt_grct_en_ewt_grct_42_main_logits_0_uas"]

[0.8571428571428571,
 0.5416666666666667,
 0.7777777777777778,
 0.8399999999999999,
 0.625,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8571428571428571,
 1.0,
 1.0,
 1.0,
 1.0,
 0.7407407407407408,
 1.0,
 0.9090909090909091,
 0.7916666666666666,
 0.9047619047619048,
 0.75,
 0.7924528301886792,
 0.8888888888888888,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9615384615384616,
 0.6521739130434783,
 0.9259259259259259,
 1.0,
 0.8461538461538461,
 1.0,
 1.0,
 0.9473684210526315,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8181818181818182,
 0.8735632183908046,
 0.96,
 0.6666666666666667,
 1.0,
 0.96875,
 0.9545454545454546,
 1.0,
 1.0,
 0.9347826086956522,
 1.0,
 0.5733333333333333,
 1.0,
 0.9166666666666666,
 1.0,
 None,
 1.0,
 1.0,
 1.0,
 0.87248322147651,
 1.0,
 0.8823529411764707,
 1.0,
 0.5490196078431373,
 0.8333333333333334,
 1.0,
 0.9333333333333333,
 1.0,
 0.7941176470588235,
 0.6,
 0.5777777777777778,
 0.6329113924050633,
 1.0,
 0.9230769230769231,
 1.0,
 0.875,
 0.9428571428571428,
 0.7042253521126761,
 1.0,
 0.4,
 0.8857142857142857,
 0.9166666666666666,
 None,
 0.5897435897435896,
 0.6779661016949153,
 0.9230769230769231,
 1.0,
 0.8125,
 0.8636363636363636,
 0.7692307692307693,
 0.49056603773584906,
 1.0,
 0.9761904761904762,
 0.9714285714285714,
 0.0,
 1.0,
 1.0,
 0.9411764705882353,
 1.0,
 0.9230769230769231,
 1.0,
 0.6666666666666666,
 0.9545454545454546,
 0.782608695652174,
 0.8,
 1.0,
 0.9130434782608695,
 0.8682170542635659,
 0.8947368421052632,
 0.9574468085106385,
 0.9666666666666667,
 1.0,
 1.0,
 0.9428571428571428,
 0.9824561403508771,
 0.6956521739130436,
 0.6666666666666666,
 1.0,
 0.9130434782608695,
 0.92,
 0.5714285714285714,
 0.75,
 0.14285714285714285,
 0.75,
 1.0,
 0.125,
 0.5714285714285714,
 0.3333333333333333,
 0.5714285714285714,
 0.125,
 0.625,
 0.75,
 1.0,
 0.7142857142857143,
 0.5833333333333334,
 1.0,
 0.5714285714285714,
 0.75,
 0.6060606060606061,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.7999999999999999,
 0.6875,
 0.9655172413793104,
 0.9056603773584906,
 1.0,
 0.68,
 0.9411764705882353,
 0.9666666666666667,
 1.0,
 1.0,
 0.8076923076923077,
 0.75,
 0.7164179104477613,
 0.647887323943662,
 0.9333333333333333,
 0.7187499999999999,
 1.0,
 0.8918918918918919,
 0.9666666666666667,
 0.9032258064516129,
 0.9090909090909091,
 0.875,
 0.8421052631578947,
 0.8495575221238938,
 0.7272727272727273,
 1.0,
 0.7272727272727273,
 0.9375,
 0.6111111111111113,
 0.9411764705882353,
 0.7142857142857143,
 0.875,
 1.0,
 0.8846153846153846,
 0.9230769230769231,
 0.9375,
 1.0,
 1.0,
 1.0,
 0.8936170212765957,
 0.9166666666666666,
 1.0,
 0.9310344827586207,
 1.0,
 0.5555555555555556,
 0.6666666666666666,
 None,
 0.5454545454545454,
 None,
 0.8672566371681416,
 1.0,
 0.9230769230769231,
 0.9375,
 1.0,
 1.0,
 0.9375,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.6206896551724138,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8387096774193549,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9523809523809523,
 1.0,
 0.9230769230769231,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8333333333333334,
 1.0,
 1.0,
 0.20000000000000004,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.875,
 0.8823529411764706,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8823529411764706,
 0.8181818181818182,
 1.0,
 0.5599999999999999,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.7368421052631579,
 1.0,
 0.8405797101449276,
 0.7368421052631579,
 1.0,
 1.0,
 0.9444444444444444,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9230769230769231,
 0.0,
 0.3333333333333333,
 0.4000000000000001,
 1.0,
 0.8000000000000002,
 1.0,
 1.0,
 None,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8703703703703703,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.6428571428571429,
 1.0,
 0.975609756097561,
 0.8333333333333334,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.875,
 0.42857142857142855,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8620689655172413,
 1.0,
 0.8666666666666667,
 0.3888888888888889,
 0.7222222222222222,
 1.0,
 0.5777777777777778,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9523809523809523,
 1.0,
 0.3684210526315789,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8947368421052632,
 1.0,
 0.85,
 0.9333333333333333,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.7368421052631577,
 0.15789473684210525,
 0.36363636363636365,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9411764705882353,
 0.9473684210526316,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9333333333333333,
 1.0,
 0.5384615384615384,
 1.0,
 1.0,
 0.6363636363636364,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8888888888888888,
 1.0,
 1.0,
 1.0,
 0.46153846153846156,
 1.0,
 0.7037037037037037,
 1.0,
 1.0,
 1.0,
 0.4411764705882353,
 0.9523809523809523,
 0.9285714285714286,
 1.0,
 1.0,
 0.6666666666666666,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8333333333333334,
 0.0,
 1.0,
 0.9545454545454546,
 1.0,
 0.5,
 1.0,
 1.0,
 1.0,
 0.9655172413793104,
 1.0,
 0.72,
 0.8620689655172413,
 1.0,
 1.0,
 1.0,
 0.5454545454545454,
 1.0,
 1.0,
 0.6666666666666667,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.4000000000000001,
 1.0,
 1.0,
 0.20000000000000004,
 1.0,
 1.0,
 0.20000000000000004,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.3333333333333333,
 1.0,
 0.8888888888888888,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9565217391304348,
 0.29411764705882354,
 1.0,
 1.0,
 0.6774193548387096,
 0.75,
 1.0,
 0.9,
 1.0,
 1.0,
 0.9,
 1.0,
 1.0,
 0.9,
 1.0,
 0.5555555555555556,
 1.0,
 1.0,
 0.9523809523809523,
 0.9545454545454546,
 1.0,
 0.25925925925925924,
 0.12500000000000003,
 1.0,
 0.875,
 0.875,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.76,
 1.0,
 0.9,
 1.0,
 1.0,
 0.9,
 1.0,
 1.0,
 1.0,
 0.76,
 0.12500000000000003,
 1.0,
 0.875,
 0.875,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.76,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8333333333333334,
 1.0,
 1.0,
 0.8571428571428571,
 0.5806451612903226,
 0.7826086956521738,
 None,
 0.8235294117647058,
 0.8333333333333334,
 None,
 1.0,
 1.0,
 0.9411764705882353,
 0.9259259259259259,
 0.5555555555555556,
 1.0,
 1.0,
 0.8235294117647058,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.7142857142857143,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9130434782608695,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8596491228070176,
 0.8333333333333334,
 1.0,
 0.8823529411764706,
 1.0,
 0.9500000000000001,
 0.967741935483871,
 1.0,
 1.0,
 0.8333333333333334,
 1.0,
 1.0,
 0.9230769230769231,
 0.8076923076923077,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9583333333333334,
 1.0,
 0.9310344827586207,
 1.0,
 0.9166666666666666,
 0.7692307692307693,
 1.0,
 0.7716535433070867,
 1.0,
 1.0,
 0.8518518518518519,
 0.4897959183673469,
 1.0,
 1.0,
 0.9705882352941176,
 0.85,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8666666666666667,
 1.0,
 1.0,
 1.0,
 1.0,
 0.875,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.4444444444444444,
 0.0,
 1.0,
 1.0,
 1.0,
 0.8863636363636365,
 None,
 0.9629629629629629,
 0.967741935483871,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.48148148148148145,
 1.0,
 1.0,
 0.75,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8461538461538461,
 0.9285714285714286,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9333333333333333,
 1.0,
 1.0,
 0.9130434782608695,
 0.3333333333333333,
 1.0,
 1.0,
 1.0,
 0.7500000000000001,
 0.7951807228915663,
 1.0,
 1.0,
 0.92,
 1.0,
 1.0,
 0.9,
 1.0,
 1.0,
 1.0,
 0.8125,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.7083333333333334,
 0.9545454545454546,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8421052631578947,
 1.0,
 0.5714285714285714,
 1.0,
 1.0,
 0.6666666666666666,
 0.625,
 0.0,
 0.8387096774193549,
 1.0,
 1.0,
 1.0,
 0.9500000000000001,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9285714285714286,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9500000000000001,
 1.0,
 0.8666666666666667,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8928571428571429,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9,
 1.0,
 0.9500000000000001,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 None,
 None,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.9090909090909091,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9,
 1.0,
 1.0,
 0.5,
 0.7142857142857143,
 0.2857142857142857,
 0.3333333333333333,
 0.5555555555555556,
 0.375,
 0.7142857142857143,
 0.22222222222222218,
 0.42857142857142855,
 0.06896551724137932,
 0.06896551724137932,
 1.0,
 0.6666666666666665,
 0.7,
 0.7272727272727273,
 1.0,
 1.0,
 1.0,
 0.8888888888888888,
 0.8947368421052632,
 0.9230769230769231,
 0.34782608695652173,
 0.75,
 1.0,
 0.7857142857142857,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9230769230769231,
 1.0,
 1.0,
 1.0,
 0.6666666666666666,
 1.0,
 1.0,
 1.0,
 1.0,
 0.10526315789473685,
 1.0,
 1.0,
 1.0,
 0.8266666666666665,
 1.0,
 1.0,
 1.0,
 0.9285714285714286,
 1.0,
 0.20000000000000004,
 1.0,
 1.0,
 1.0,
 1.0,
 0.625,
 1.0,
 0.9069767441860465,
 0.25,
 1.0,
 0.7586206896551724,
 0.9,
 1.0,
 1.0,
 1.0,
 0.9444444444444444,
 1.0,
 0.42857142857142855,
 1.0,
 0.8536585365853658,
 1.0,
 0.47368421052631576,
 None,
 0.8571428571428571,
 1.0,
 None,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.3333333333333333,
 0.9615384615384616,
 0.9473684210526315,
 1.0,
 0.7777777777777778,
 1.0,
 0.7674418604651162,
 1.0,
 1.0,
 0.9074074074074074,
 0.9285714285714286,
 1.0,
 0.875,
 1.0,
 1.0,
 1.0,
 0.7222222222222222,
 1.0,
 0.75,
 0.20000000000000004,
 0.8076923076923077,
 0.9130434782608695,
 0.9259259259259259,
 1.0,
 0.926829268292683,
 0.9545454545454546,
 1.0,
 1.0,
 0.9411764705882353,
 0.7560975609756099,
 1.0,
 1.0,
 0.9130434782608695,
 1.0,
 1.0,
 0.8000000000000002,
 0.6823529411764706,
 0.9767441860465116,
 1.0,
 1.0,
 0.3,
 None,
 None,
 0.8333333333333334,
 0.9795918367346939,
 0.9642857142857143,
 0.6857142857142857,
 0.0,
 1.0,
 1.0,
 1.0,
 0.47058823529411764,
 0.6666666666666666,
 0.6666666666666666,
 0.6,
 0.4897959183673469,
 1.0,
 0.6666666666666666,
 0.9655172413793104,
 0.875,
 0.8181818181818182,
 1.0,
 0.3333333333333333,
 0.9354838709677419,
 0.9411764705882353,
 1.0,
 1.0,
 0.9473684210526315,
 0.391304347826087,
 0.9629629629629629,
 1.0,
 1.0,
 0.8181818181818182,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9333333333333333,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8947368421052632,
 0.08695652173913043,
 0.5454545454545454,
 0.7,
 1.0,
 1.0,
 0.8947368421052632,
 0.75,
 0.896551724137931,
 1.0,
 0.5,
 1.0,
 1.0,
 1.0,
 0.8235294117647058,
 0.8000000000000002,
 0.27906976744186046,
 0.8636363636363636,
 0.35714285714285715,
 1.0,
 0.9583333333333334,
 1.0,
 1.0,
 1.0,
 0.8333333333333334,
 0.9393939393939394,
 0.9500000000000001,
 1.0,
 0.75,
 0.8888888888888888,
 0.9333333333333333,
 0.3333333333333333,
 1.0,
 0.7936507936507936,
 1.0,
 1.0,
 1.0,
 0.9444444444444444,
 1.0,
 0.9523809523809523,
 0.9,
 0.6666666666666666,
 1.0,
 1.0,
 1.0,
 0.8181818181818182,
 0.875,
 0.0,
 1.0,
 1.0,
 0.9032258064516129,
 0.49056603773584906,
 0.9428571428571428,
 1.0,
 0.888888888888889,
 0.76,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9523809523809523,
 0.8717948717948718,
 ...]

In [3]:
data_dict.keys()

dict_keys(['metrics_Qwen3_8B_en_ewt_grct_en_ewt_grct_42_original_logits_4.jsonl', 'metrics_Qwen3_0_6B_en_ewt_grct_en_ewt_grct_42_original_logits_0.jsonl', 'metrics_Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct_42_original_logits_0.jsonl', 'metrics_Qwen3_0_6B_fr_gsd_grct_fr_gsd_42_original_logits_0.jsonl', 'metrics_Qwen3_0_6B_ja_gsd_grct_ja_gsd_grct_42_original_logits_0.jsonl', 'metrics_Qwen3_0_6B_ru_syntagrus_grct_ru_syntagrus_42_original_logits_0.jsonl', 'metrics_Qwen3_0_6B_zh_gsd_grct_zh_gsd_grct_42_original_logits_0.jsonl', 'metrics_Qwen3_4B_en_ewt_grct_en_ewt_grct_42_original_logits_2.jsonl', 'metrics_Qwen3_4B_fi_ftb_grct_fi_ftb_grct_42_original_logits_2.jsonl', 'metrics_Qwen3_4B_ja_gsd_grct_ja_gsd_grct_42_original_logits_2.jsonl', 'metrics_Qwen3_4B_ru_syntagrus_grct_ru_syntagrus_42_original_logits_3.jsonl', 'metrics_Qwen3_4B_zh_gsd_grct_zh_gsd_grct_42_original_logits_2.jsonl', 'metrics_Qwen3_4B_zh_gsd_grct_zh_gsd_grct_42_original_logits_3.jsonl', 'metrics_Qwen3_8B_fi_ftb_grct_fi_ftb_grct_42_original_logits_4.jsonl', 'metrics_Qwen3_8B_fr_gsd_grct_fr_gsd_42_original_logits_4.jsonl', 'metrics_Qwen3_8B_ja_gsd_grct_ja_gsd_grct_42_original_logits_4.jsonl', 'metrics_Qwen3_8B_ru_syntagrus_grct_ru_syntagrus_42_original_logits_6.jsonl', 'metrics_Qwen3_8B_zh_gsd_grct_zh_gsd_grct_42_original_logits_4.jsonl', 'metrics_Qwen3_8B_zh_gsd_grct_zh_gsd_grct_42_original_logits_6.jsonl', 'metrics_Qwen3_8B_fi_ftb_grct_fi_ftb_grct_42_main_logits_2.jsonl', 'metrics_Qwen3_8B_fr_gsd_grct_fr_gsd_42_main_logits_2.jsonl', 'metrics_Qwen3_8B_ja_gsd_grct_ja_gsd_grct_42_main_logits_2.jsonl', 'metrics_Qwen3_8B_zh_gsd_grct_zh_gsd_grct_42_main_logits_2.jsonl', 'metrics_Qwen3_0_6B_en_ewt_grct_en_ewt_grct_42_main_logits_0.jsonl', 'metrics_Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct_42_main_logits_0.jsonl', 'metrics_Qwen3_0_6B_fr_gsd_grct_fr_gsd_42_main_logits_0.jsonl', 'metrics_Qwen3_0_6B_ja_gsd_grct_ja_gsd_grct_42_main_logits_0.jsonl', 'metrics_Qwen3_0_6B_zh_gsd_grct_zh_gsd_grct_42_main_logits_0.jsonl', 'metrics_Qwen3_4B_en_ewt_grct_en_ewt_grct_42_main_logits_1.jsonl', 'metrics_Qwen3_4B_fi_ftb_grct_fi_ftb_grct_42_main_logits_1.jsonl', 'metrics_Qwen3_4B_fr_gsd_grct_fr_gsd_42_main_logits_1.jsonl', 'metrics_Qwen3_4B_ja_gsd_grct_ja_gsd_grct_42_main_logits_1.jsonl', 'metrics_Qwen3_4B_zh_gsd_grct_zh_gsd_grct_42_main_logits_1.jsonl', 'metrics_Qwen3_8B_en_ewt_grct_en_ewt_grct_42_main_logits_2.jsonl', 'metrics_Qwen3_0_6B_en_ewt_grct_en_ewt_grct_42_root_logits_0.jsonl', 'metrics_Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct_42_root_logits_0.jsonl', 'metrics_Qwen3_0_6B_fr_gsd_grct_fr_gsd_42_root_logits_0.jsonl', 'metrics_Qwen3_0_6B_ja_gsd_grct_ja_gsd_grct_42_root_logits_0.jsonl', 'metrics_Qwen3_0_6B_zh_gsd_grct_zh_gsd_grct_42_root_logits_0.jsonl', 'metrics_Qwen3_4B_en_ewt_grct_en_ewt_grct_42_root_logits_1.jsonl', 'metrics_Qwen3_4B_fi_ftb_grct_fi_ftb_grct_42_root_logits_1.jsonl', 'metrics_Qwen3_4B_fr_gsd_grct_fr_gsd_42_root_logits_1.jsonl', 'metrics_Qwen3_4B_ja_gsd_grct_ja_gsd_grct_42_root_logits_1.jsonl', 'metrics_Qwen3_8B_en_ewt_grct_en_ewt_grct_42_root_logits_2.jsonl', 'metrics_Qwen3_8B_fi_ftb_grct_fi_ftb_grct_42_root_logits_2.jsonl', 'metrics_Qwen3_8B_fr_gsd_grct_fr_gsd_42_root_logits_2.jsonl', 'metrics_Qwen3_8B_ja_gsd_grct_ja_gsd_grct_42_root_logits_2.jsonl', 'metrics_Qwen3_8B_zh_gsd_grct_zh_gsd_grct_42_root_logits_2.jsonl', 'metrics_Qwen3_4B_zh_gsd_grct_zh_gsd_grct_42_root_logits_1.jsonl'])

In [4]:
d = uas_pd_results["Qwen3_0_6B_en_ewt_grct_en_ewt_grct"]

[(k, len(d[k])) for k in d]

[('original_logits', 2077), ('main_logits', 2077), ('root_logits', 2077)]

In [5]:
13, 18, 22

(13, 18, 22)

In [6]:
for i in range(19, 1775):
    if uas_pd_results["Qwen3_0_6B_en_ewt_grct_en_ewt_grct"]['main_logits'][i] != \
        uas_pd_results["Qwen3_0_6B_en_ewt_grct_en_ewt_grct"]['original_logits'][i]:
      if uas_pd_results["Qwen3_0_6B_en_ewt_grct_en_ewt_grct"]['original_logits'][i] is not None:
        print(i)
        break

19

In [7]:
uas_pd_results["Qwen3_0_6B_en_ewt_grct_en_ewt_grct"]['original_logits'][70]

np.float64(0.98)

In [8]:
uas_pd_results["Qwen3_0_6B_en_ewt_grct_en_ewt_grct"]['main_logits'][70]

np.float64(0.5777777777777778)

In [9]:
'main_logits' in uas_pd_results['Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct'].columns

True

In [10]:
for exp in experiments:
    if exp not in wrong_experiments:
        print(exp, uas_pd_results[exp].keys().values)
        if 'main_logits' in uas_pd_results[exp].columns and 'original_logits' in uas_pd_results[exp].columns:
            print('o<m', sum(
                (uas_pd_results[exp]['original_logits'] < uas_pd_results[exp]['main_logits']) &
                     (uas_pd_results[exp]['main_logits'] > 0)))
            print('o<r', sum((uas_pd_results[exp]['original_logits'] < uas_pd_results[exp]['root_logits']) &
                            (uas_pd_results[exp]['original_logits'] > 0)))
            print('o>r', sum((uas_pd_results[exp]['original_logits'] > uas_pd_results[exp]['root_logits']) &
                            (uas_pd_results[exp]['root_logits'] > 0)))

        else:
            print(-1)

Qwen3_8B_ru_syntagrus_grct_ru_syntagrus ['original_logits']
-1
Qwen3_8B_fi_ftb_grct_fi_ftb_grct ['original_logits' 'main_logits' 'root_logits']
o<m 2
o<r 4
o>r 5
Qwen3_8B_zh_gsd_grct_zh_gsd_grct ['original_logits' 'main_logits' 'root_logits']
o<m 1
o<r 1
o>r 71
Qwen3_8B_fr_gsd_grct_fr_gsd ['original_logits' 'main_logits' 'root_logits']
o<m 1
o<r 0
o>r 24
Qwen3_8B_ja_gsd_grct_ja_gsd_grct ['original_logits' 'main_logits' 'root_logits']
o<m 3
o<r 3
o>r 282
Qwen3_0_6B_en_ewt_grct_en_ewt_grct ['original_logits' 'main_logits' 'root_logits']
o<m 4
o<r 5
o>r 12
Qwen3_4B_fr_gsd_grct_fr_gsd ['main_logits' 'root_logits']
-1
Qwen3_0_6B_fr_gsd_grct_fr_gsd ['original_logits' 'main_logits' 'root_logits']
o<m 0
o<r 0
o>r 14
Qwen3_0_6B_zh_gsd_grct_zh_gsd_grct ['original_logits' 'main_logits' 'root_logits']
o<m 4
o<r 2
o>r 184
Qwen3_4B_en_ewt_grct_en_ewt_grct ['original_logits' 'main_logits' 'root_logits']
o<m 25
o<r 25
o>r 24
Qwen3_4B_fi_ftb_grct_fi_ftb_grct ['original_logits' 'main_logits' 'root_logits']
o<m 2
o<r 4
o>r 6
Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct ['original_logits' 'main_logits' 'root_logits']
o<m 13
o<r 12
o>r 6
Qwen3_0_6B_ja_gsd_grct_ja_gsd_grct ['original_logits' 'main_logits' 'root_logits']
o<m 0
o<r 1
o>r 302
Qwen3_0_6B_ru_syntagrus_grct_ru_syntagrus ['original_logits']
-1
Qwen3_4B_ja_gsd_grct_ja_gsd_grct ['original_logits' 'main_logits' 'root_logits']
o<m 3
o<r 3
o>r 297
Qwen3_4B_zh_gsd_grct_zh_gsd_grct ['original_logits' 'main_logits' 'root_logits']
o<m 3
o<r 3
o>r 54
Qwen3_8B_en_ewt_grct_en_ewt_grct ['original_logits' 'main_logits' 'root_logits']
o<m 2
o<r 4
o>r 7
Qwen3_4B_ru_syntagrus_grct_ru_syntagrus ['original_logits']
-1

In [11]:
df = uas_pd_results['Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct']

df[df['main_logits'] < df['original_logits']]

      original_logits  main_logits  root_logits
72           1.000000     0.700000     0.700000
88           0.875000     0.600000     0.600000
263          0.863636     0.818182     0.863636
306          1.000000     0.000000     0.000000
799          0.733333     0.645161     0.645161
1129         0.777778     0.722222     0.722222
1169         0.923077     0.857143     0.857143

In [12]:
uas_pd_results[exp]

      original_logits
0            1.000000
1            0.705882
2            1.000000
3                 NaN
4            0.857143
...               ...
8795         1.000000
8796         1.000000
8797         0.900000
8798         1.000000
8799         1.000000

[8800 rows x 1 columns]

In [13]:
for exp in experiments:
  if "zh" not in exp and "ja" not in exp:
    for exp_type in uas_pd_results[exp].keys():
        df = uas_pd_results[exp][exp_type]
        print(exp, exp_type, sum(df.isnull()))
    print()

Qwen3_8B_ru_syntagrus_grct_ru_syntagrus original_logits 32

Qwen3_8B_fi_ftb_grct_fi_ftb_grct original_logits 25
Qwen3_8B_fi_ftb_grct_fi_ftb_grct main_logits 5
Qwen3_8B_fi_ftb_grct_fi_ftb_grct root_logits 6

Qwen3_8B_fr_gsd_grct_fr_gsd original_logits 19
Qwen3_8B_fr_gsd_grct_fr_gsd main_logits 2
Qwen3_8B_fr_gsd_grct_fr_gsd root_logits 2

Qwen3_0_6B_en_ewt_grct_en_ewt_grct original_logits 134
Qwen3_0_6B_en_ewt_grct_en_ewt_grct main_logits 28
Qwen3_0_6B_en_ewt_grct_en_ewt_grct root_logits 29

Qwen3_4B_fr_gsd_grct_fr_gsd main_logits 8
Qwen3_4B_fr_gsd_grct_fr_gsd root_logits 7

Qwen3_0_6B_fr_gsd_grct_fr_gsd original_logits 71
Qwen3_0_6B_fr_gsd_grct_fr_gsd main_logits 11
Qwen3_0_6B_fr_gsd_grct_fr_gsd root_logits 11

Qwen3_4B_en_ewt_grct_en_ewt_grct original_logits 83
Qwen3_4B_en_ewt_grct_en_ewt_grct main_logits 7
Qwen3_4B_en_ewt_grct_en_ewt_grct root_logits 7

Qwen3_4B_fi_ftb_grct_fi_ftb_grct original_logits 37
Qwen3_4B_fi_ftb_grct_fi_ftb_grct main_logits 5
Qwen3_4B_fi_ftb_grct_fi_ftb_grct root_logits 5

Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct original_logits 59
Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct main_logits 8
Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct root_logits 9

Qwen3_0_6B_ru_syntagrus_grct_ru_syntagrus original_logits 458

Qwen3_8B_en_ewt_grct_en_ewt_grct original_logits 40
Qwen3_8B_en_ewt_grct_en_ewt_grct main_logits 4
Qwen3_8B_en_ewt_grct_en_ewt_grct root_logits 4

Qwen3_4B_ru_syntagrus_grct_ru_syntagrus original_logits 251

In [14]:
for exp in experiments:
  if "zh" in exp or "ja" in exp:
    for exp_type in uas_pd_results[exp].keys():
        df = uas_pd_results[exp][exp_type]
        print(exp, exp_type, sum(df.isnull()))
    print()

Qwen3_8B_zh_gsd_grct_zh_gsd_grct original_logits 37
Qwen3_8B_zh_gsd_grct_zh_gsd_grct main_logits 421
Qwen3_8B_zh_gsd_grct_zh_gsd_grct root_logits 422

Qwen3_8B_ja_gsd_grct_ja_gsd_grct original_logits 45
Qwen3_8B_ja_gsd_grct_ja_gsd_grct main_logits 227
Qwen3_8B_ja_gsd_grct_ja_gsd_grct root_logits 225

Qwen3_0_6B_zh_gsd_grct_zh_gsd_grct original_logits 252
Qwen3_0_6B_zh_gsd_grct_zh_gsd_grct main_logits 125
Qwen3_0_6B_zh_gsd_grct_zh_gsd_grct root_logits 121

Qwen3_0_6B_ja_gsd_grct_ja_gsd_grct original_logits 180
Qwen3_0_6B_ja_gsd_grct_ja_gsd_grct main_logits 76
Qwen3_0_6B_ja_gsd_grct_ja_gsd_grct root_logits 75

Qwen3_4B_ja_gsd_grct_ja_gsd_grct original_logits 57
Qwen3_4B_ja_gsd_grct_ja_gsd_grct main_logits 194
Qwen3_4B_ja_gsd_grct_ja_gsd_grct root_logits 193

Qwen3_4B_zh_gsd_grct_zh_gsd_grct original_logits 83
Qwen3_4B_zh_gsd_grct_zh_gsd_grct main_logits 435
Qwen3_4B_zh_gsd_grct_zh_gsd_grct root_logits 436

In [15]:
for exp in experiments:
    for exp_type in uas_pd_results[exp].keys():
        print(exp, exp_type)
        df = uas_pd_results[exp][exp_type]
        print("[" + ", ".join(map(str, df[df.isnull()].index.values)) + "]")

Qwen3_8B_ru_syntagrus_grct_ru_syntagrus original_logits
[31, 66, 135, 226, 489, 1126, 1374, 1398, 1486, 1530, 1954, 2206, 2314, 2919, 3125, 3457, 3996, 4182, 4315, 4884, 5149, 5466, 5477, 5806, 6850, 7414, 7417, 7497, 7661, 7700, 8470, 8729]
Qwen3_8B_fi_ftb_grct_fi_ftb_grct original_logits
[117, 280, 340, 343, 360, 464, 768, 786, 910, 924, 952, 998, 1037, 1093, 1094, 1095, 1260, 1313, 1457, 1485, 1548, 1670, 1726, 1768, 1815]
Qwen3_8B_fi_ftb_grct_fi_ftb_grct main_logits
[280, 340, 1094, 1715, 1815]
Qwen3_8B_fi_ftb_grct_fi_ftb_grct root_logits
[280, 340, 768, 1094, 1715, 1815]
Qwen3_8B_zh_gsd_grct_zh_gsd_grct original_logits
[5, 14, 17, 44, 50, 51, 62, 105, 129, 141, 142, 147, 200, 211, 213, 214, 277, 278, 307, 309, 312, 316, 340, 374, 388, 399, 434, 437, 444, 446, 448, 453, 456, 458, 477, 498, 499]
Qwen3_8B_zh_gsd_grct_zh_gsd_grct main_logits
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 35, 36, 38, 39, 41, 42, 43, 44, 45, 46, 49, 50, 51, 52, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 84, 86, 87, 88, 89, 90, 91, 93, 94, 95, 96, 97, 98, 99, 101, 103, 104, 106, 107, 108, 109, 111, 112, 113, 114, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 127, 128, 129, 130, 131, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 145, 146, 147, 148, 149, 150, 153, 154, 155, 156, 157, 158, 159, 161, 162, 163, 164, 165, 166, 168, 170, 171, 172, 173, 174, 175, 176, 177, 178, 180, 181, 182, 183, 184, 185, 186, 188, 189, 190, 191, 192, 193, 194, 196, 197, 198, 199, 200, 201, 202, 203, 205, 206, 208, 209, 210, 211, 212, 213, 214, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 230, 231, 232, 233, 234, 235, 237, 238, 240, 241, 242, 243, 244, 245, 246, 247, 248, 250, 251, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 264, 266, 267, 268, 269, 270, 271, 272, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 290, 291, 292, 293, 294, 296, 297, 298, 299, 300, 301, 302, 303, 305, 306, 307, 308, 309, 310, 311, 312, 315, 316, 317, 318, 319, 322, 323, 324, 325, 326, 327, 328, 329, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 343, 344, 346, 347, 348, 349, 350, 351, 352, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 377, 378, 380, 383, 384, 385, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 406, 408, 409, 410, 411, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 425, 427, 428, 429, 431, 433, 434, 435, 436, 437, 438, 440, 441, 442, 443, 444, 445, 446, 447, 450, 451, 452, 454, 456, 457, 459, 460, 461, 462, 464, 465, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 499]
Qwen3_8B_zh_gsd_grct_zh_gsd_grct root_logits
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 38, 39, 41, 42, 43, 44, 45, 46, 49, 50, 51, 52, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 84, 86, 87, 88, 89, 90, 91, 93, 94, 95, 96, 97, 98, 99, 101, 103, 104, 106, 107, 108, 109, 111, 112, 113, 114, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 127, 128, 129, 130, 131, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 145, 146, 147, 148, 149, 150, 153, 154, 155, 156, 157, 158, 159, 161, 162, 163, 164, 165, 166, 168, 170, 171, 172, 173, 174, 175, 176, 177, 178, 180, 181, 182, 183, 184, 185, 186, 188, 189, 190, 191, 192, 193, 194, 196, 197, 198, 199, 200, 201, 202, 203, 205, 206, 208, 209, 210, 211, 212, 213, 214, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 230, 231, 232, 233, 234, 235, 237, 238, 240, 241, 242, 243, 244, 245, 246, 247, 248, 250, 251, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 264, 266, 267, 268, 269, 270, 271, 272, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 290, 291, 292, 293, 294, 296, 297, 298, 299, 300, 301, 302, 303, 305, 306, 307, 308, 309, 310, 311, 312, 315, 316, 317, 318, 319, 322, 323, 324, 325, 326, 327, 328, 329, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 343, 344, 346, 347, 348, 349, 350, 351, 352, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 377, 378, 380, 383, 384, 385, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 406, 408, 409, 410, 411, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 425, 427, 428, 429, 431, 433, 434, 435, 436, 437, 438, 440, 441, 442, 443, 444, 445, 446, 447, 450, 451, 452, 454, 456, 457, 459, 460, 461, 464, 465, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 499]
Qwen3_8B_fr_gsd_grct_fr_gsd original_logits
[14, 20, 29, 36, 46, 61, 62, 64, 91, 103, 122, 144, 192, 197, 275, 325, 351, 386, 405]
Qwen3_8B_fr_gsd_grct_fr_gsd main_logits
[14, 62]
Qwen3_8B_fr_gsd_grct_fr_gsd root_logits
[14, 62]
Qwen3_8B_ja_gsd_grct_ja_gsd_grct original_logits
[34, 35, 39, 40, 46, 51, 73, 76, 87, 113, 129, 145, 164, 180, 200, 219, 229, 240, 241, 246, 251, 256, 296, 298, 307, 319, 321, 328, 340, 353, 373, 386, 393, 415, 442, 444, 447, 466, 468, 493, 495, 496, 508, 524, 530]
Qwen3_8B_ja_gsd_grct_ja_gsd_grct main_logits
[0, 2, 18, 33, 35, 38, 46, 49, 51, 54, 61, 64, 75, 76, 78, 87, 88, 90, 92, 99, 100, 101, 104, 105, 106, 107, 108, 110, 111, 112, 113, 115, 116, 117, 118, 123, 124, 125, 126, 127, 128, 129, 131, 133, 134, 136, 137, 140, 142, 146, 148, 149, 150, 153, 156, 158, 159, 160, 161, 163, 164, 168, 169, 170, 171, 174, 177, 178, 180, 181, 185, 186, 187, 188, 190, 191, 193, 194, 195, 197, 200, 201, 204, 208, 211, 215, 218, 219, 220, 222, 225, 229, 230, 237, 242, 243, 244, 245, 247, 249, 252, 255, 257, 260, 261, 263, 265, 266, 267, 268, 274, 275, 276, 277, 279, 284, 285, 286, 292, 295, 296, 297, 298, 299, 301, 304, 305, 306, 307, 310, 312, 314, 315, 319, 320, 321, 322, 326, 332, 338, 340, 342, 344, 348, 350, 357, 358, 360, 365, 366, 367, 369, 376, 378, 379, 380, 381, 382, 384, 386, 391, 392, 393, 395, 398, 402, 407, 410, 412, 415, 417, 418, 422, 424, 429, 431, 438, 439, 441, 442, 444, 446, 447, 448, 449, 450, 453, 455, 457, 459, 460, 462, 463, 464, 466, 470, 471, 472, 474, 479, 481, 484, 487, 489, 490, 491, 494, 495, 496, 497, 505, 506, 509, 511, 512, 513, 515, 520, 521, 524, 525, 528, 530, 532, 535, 539, 542]
Qwen3_8B_ja_gsd_grct_ja_gsd_grct root_logits
[0, 2, 18, 33, 35, 38, 46, 49, 51, 54, 61, 64, 75, 76, 78, 87, 88, 90, 92, 99, 100, 101, 104, 105, 106, 107, 108, 110, 111, 112, 113, 115, 116, 117, 118, 123, 124, 125, 126, 127, 128, 129, 131, 133, 134, 136, 137, 140, 142, 146, 148, 149, 150, 153, 156, 158, 159, 160, 161, 163, 164, 168, 169, 170, 171, 174, 177, 178, 180, 181, 185, 186, 187, 188, 190, 191, 193, 194, 195, 197, 200, 201, 204, 208, 211, 215, 218, 219, 220, 222, 225, 229, 230, 237, 242, 243, 244, 245, 247, 249, 252, 255, 257, 260, 261, 263, 265, 266, 267, 268, 274, 275, 276, 277, 279, 284, 285, 286, 292, 295, 296, 297, 298, 299, 301, 304, 305, 306, 307, 310, 312, 314, 315, 319, 320, 321, 322, 326, 332, 338, 340, 342, 344, 348, 350, 357, 358, 360, 365, 366, 367, 369, 376, 379, 380, 381, 382, 384, 386, 391, 392, 393, 395, 398, 402, 407, 410, 412, 415, 417, 418, 422, 424, 429, 431, 438, 439, 441, 442, 444, 446, 447, 448, 449, 450, 453, 455, 457, 459, 460, 462, 463, 464, 466, 470, 471, 472, 474, 479, 481, 484, 487, 489, 490, 491, 494, 495, 496, 497, 505, 506, 511, 512, 513, 515, 520, 521, 524, 525, 528, 530, 532, 535, 539, 542]
Qwen3_0_6B_en_ewt_grct_en_ewt_grct original_logits
[1, 4, 15, 19, 21, 29, 43, 51, 55, 59, 61, 69, 71, 77, 79, 82, 83, 84, 89, 90, 104, 109, 115, 138, 153, 161, 162, 163, 165, 184, 189, 196, 198, 199, 219, 290, 308, 354, 414, 429, 472, 493, 502, 511, 512, 521, 531, 533, 536, 594, 598, 630, 648, 673, 759, 760, 781, 783, 784, 812, 844, 847, 869, 877, 882, 889, 894, 895, 908, 921, 939, 954, 971, 979, 989, 999, 1023, 1031, 1033, 1034, 1140, 1164, 1189, 1208, 1211, 1217, 1226, 1232, 1299, 1354, 1360, 1367, 1371, 1389, 1423, 1431, 1438, 1448, 1458, 1460, 1468, 1469, 1471, 1473, 1502, 1524, 1525, 1538, 1541, 1564, 1576, 1582, 1639, 1643, 1644, 1645, 1655, 1656, 1660, 1666, 1730, 1762, 1794, 1828, 1847, 1852, 1858, 1871, 1882, 1900, 1912, 1939, 1992, 2010]
Qwen3_0_6B_en_ewt_grct_en_ewt_grct main_logits
[55, 82, 196, 198, 308, 533, 536, 630, 759, 760, 844, 847, 894, 895, 1023, 1034, 1189, 1354, 1360, 1389, 1438, 1460, 1644, 1655, 1656, 1847, 1852, 1871]
Qwen3_0_6B_en_ewt_grct_en_ewt_grct root_logits
[43, 77, 82, 196, 198, 308, 533, 536, 630, 759, 760, 844, 847, 894, 895, 1023, 1034, 1189, 1354, 1360, 1389, 1438, 1460, 1644, 1655, 1656, 1847, 1852, 1871]
Qwen3_4B_fr_gsd_grct_fr_gsd main_logits
[4, 15, 114, 126, 196, 309, 318, 391]
Qwen3_4B_fr_gsd_grct_fr_gsd root_logits
[4, 15, 126, 196, 309, 318, 391]
Qwen3_0_6B_fr_gsd_grct_fr_gsd original_logits
[6, 11, 18, 29, 42, 45, 46, 49, 54, 55, 62, 66, 69, 70, 74, 80, 82, 88, 89, 95, 97, 107, 113, 117, 123, 133, 135, 142, 143, 145, 161, 170, 175, 181, 186, 190, 192, 195, 197, 200, 201, 226, 230, 239, 250, 251, 256, 275, 279, 288, 295, 301, 305, 318, 319, 325, 343, 348, 352, 360, 369, 370, 371, 377, 378, 385, 386, 387, 405, 411, 412]
Qwen3_0_6B_fr_gsd_grct_fr_gsd main_logits
[2, 15, 22, 33, 64, 145, 302, 345, 361, 371, 385]
Qwen3_0_6B_fr_gsd_grct_fr_gsd root_logits
[2, 15, 22, 33, 64, 145, 302, 345, 361, 371, 385]
Qwen3_0_6B_zh_gsd_grct_zh_gsd_grct original_logits
[3, 6, 8, 9, 11, 12, 14, 15, 16, 17, 18, 21, 22, 23, 24, 27, 29, 30, 39, 40, 43, 44, 49, 51, 53, 55, 56, 57, 58, 60, 62, 63, 65, 68, 69, 70, 71, 75, 76, 79, 83, 84, 85, 86, 91, 94, 96, 98, 100, 101, 103, 104, 106, 111, 115, 116, 119, 120, 121, 122, 123, 124, 128, 129, 133, 134, 135, 138, 139, 140, 141, 142, 144, 145, 150, 153, 155, 159, 160, 161, 168, 169, 170, 171, 172, 174, 177, 178, 179, 180, 181, 183, 184, 185, 186, 188, 193, 195, 196, 197, 198, 199, 203, 204, 205, 206, 208, 211, 213, 214, 216, 221, 222, 227, 229, 230, 233, 235, 236, 237, 239, 240, 246, 248, 250, 251, 252, 253, 254, 255, 257, 258, 259, 261, 265, 266, 268, 273, 275, 276, 277, 278, 279, 282, 283, 285, 289, 290, 292, 294, 296, 298, 299, 301, 303, 305, 307, 308, 309, 312, 315, 316, 317, 320, 322, 324, 326, 328, 329, 331, 332, 333, 334, 336, 337, 338, 340, 341, 345, 348, 350, 351, 353, 354, 356, 358, 359, 360, 365, 368, 369, 370, 372, 373, 374, 376, 382, 383, 385, 388, 396, 398, 399, 405, 406, 409, 411, 412, 413, 415, 416, 417, 418, 420, 423, 427, 428, 431, 433, 434, 436, 437, 438, 439, 444, 445, 446, 448, 453, 454, 456, 458, 459, 460, 462, 467, 470, 471, 472, 476, 477, 478, 479, 482, 483, 489, 492, 495, 496, 497, 498, 499]
Qwen3_0_6B_zh_gsd_grct_zh_gsd_grct main_logits
[1, 3, 5, 8, 9, 11, 12, 16, 17, 18, 27, 30, 41, 42, 43, 44, 46, 55, 57, 58, 60, 61, 63, 71, 84, 86, 91, 95, 96, 98, 99, 103, 112, 115, 126, 133, 145, 147, 150, 151, 152, 153, 155, 157, 160, 166, 168, 174, 177, 179, 187, 188, 191, 193, 196, 198, 199, 204, 208, 220, 227, 229, 233, 235, 236, 240, 246, 248, 250, 252, 253, 257, 259, 260, 261, 268, 269, 272, 273, 275, 276, 281, 287, 297, 298, 300, 301, 303, 307, 309, 316, 317, 323, 324, 329, 336, 345, 354, 357, 358, 373, 377, 381, 397, 406, 407, 409, 411, 414, 416, 417, 420, 429, 431, 436, 441, 446, 451, 454, 458, 468, 470, 482, 495, 498]
Qwen3_0_6B_zh_gsd_grct_zh_gsd_grct root_logits
[1, 3, 5, 8, 9, 11, 12, 14, 16, 18, 30, 41, 42, 43, 44, 46, 55, 57, 58, 60, 61, 63, 71, 84, 86, 91, 95, 96, 98, 99, 103, 112, 115, 126, 133, 145, 147, 150, 151, 152, 153, 155, 157, 160, 166, 174, 177, 179, 187, 188, 191, 193, 196, 198, 199, 204, 208, 220, 227, 229, 233, 235, 236, 240, 246, 248, 250, 252, 253, 257, 260, 261, 268, 269, 272, 273, 275, 276, 281, 287, 297, 298, 300, 301, 303, 307, 309, 316, 317, 323, 324, 329, 336, 345, 354, 357, 358, 377, 381, 397, 406, 407, 409, 411, 414, 416, 417, 420, 429, 431, 436, 441, 446, 451, 454, 458, 468, 470, 482, 495, 498]
Qwen3_4B_en_ewt_grct_en_ewt_grct original_logits
[21, 40, 51, 55, 59, 63, 69, 83, 89, 94, 98, 101, 103, 109, 114, 156, 170, 185, 189, 196, 198, 249, 340, 394, 414, 570, 572, 575, 597, 598, 629, 693, 760, 798, 812, 832, 875, 895, 898, 899, 900, 916, 917, 950, 954, 963, 966, 999, 1000, 1003, 1023, 1031, 1033, 1035, 1076, 1140, 1143, 1164, 1198, 1254, 1306, 1318, 1382, 1391, 1392, 1405, 1415, 1438, 1483, 1521, 1524, 1538, 1582, 1627, 1686, 1790, 1831, 1833, 1871, 1900, 1980, 2005, 2056]
Qwen3_4B_en_ewt_grct_en_ewt_grct main_logits
[51, 101, 414, 1331, 1360, 1382, 1392]
Qwen3_4B_en_ewt_grct_en_ewt_grct root_logits
[51, 101, 414, 1331, 1360, 1382, 1392]
Qwen3_4B_fi_ftb_grct_fi_ftb_grct original_logits
[61, 72, 153, 225, 236, 247, 254, 263, 549, 586, 608, 623, 730, 819, 863, 896, 917, 924, 957, 1037, 1094, 1098, 1143, 1270, 1275, 1277, 1436, 1484, 1562, 1576, 1588, 1629, 1689, 1696, 1713, 1768, 1824]
Qwen3_4B_fi_ftb_grct_fi_ftb_grct main_logits
[225, 236, 896, 1576, 1588]
Qwen3_4B_fi_ftb_grct_fi_ftb_grct root_logits
[225, 236, 896, 1576, 1588]
Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct original_logits
[58, 59, 100, 215, 225, 228, 281, 321, 322, 323, 356, 464, 465, 505, 533, 549, 553, 606, 637, 650, 658, 709, 806, 816, 819, 838, 865, 910, 914, 916, 924, 946, 972, 998, 1093, 1098, 1102, 1116, 1141, 1143, 1147, 1222, 1354, 1366, 1386, 1401, 1425, 1449, 1473, 1484, 1608, 1629, 1658, 1677, 1715, 1764, 1815, 1817, 1833]
Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct main_logits
[321, 658, 865, 1098, 1141, 1386, 1588, 1629]
Qwen3_0_6B_fi_ftb_grct_fi_ftb_grct root_logits
[321, 658, 865, 928, 1098, 1141, 1386, 1588, 1629]
Qwen3_0_6B_ja_gsd_grct_ja_gsd_grct original_logits
[7, 10, 21, 27, 33, 34, 42, 46, 47, 48, 50, 51, 59, 61, 64, 66, 68, 73, 74, 77, 83, 84, 87, 90, 93, 94, 97, 98, 102, 104, 106, 108, 112, 113, 114, 115, 116, 117, 123, 125, 130, 131, 134, 138, 139, 142, 146, 155, 159, 160, 161, 163, 164, 169, 171, 176, 180, 181, 183, 190, 201, 202, 203, 205, 207, 210, 211, 212, 215, 219, 221, 222, 225, 226, 228, 229, 230, 231, 241, 248, 249, 251, 253, 255, 256, 258, 262, 263, 264, 265, 273, 284, 285, 288, 295, 296, 298, 302, 303, 306, 309, 312, 314, 321, 328, 334, 335, 337, 338, 339, 342, 344, 345, 346, 350, 353, 355, 357, 358, 368, 373, 375, 378, 379, 381, 384, 385, 390, 391, 393, 398, 401, 404, 408, 410, 414, 416, 426, 431, 438, 444, 445, 446, 447, 450, 451, 452, 455, 466, 467, 469, 470, 472, 473, 475, 478, 480, 483, 485, 489, 490, 493, 494, 495, 500, 501, 502, 503, 506, 508, 511, 512, 514, 524, 526, 528, 531, 536, 540, 542]
Qwen3_0_6B_ja_gsd_grct_ja_gsd_grct main_logits
[18, 20, 43, 46, 52, 79, 80, 87, 111, 112, 113, 114, 115, 118, 123, 124, 125, 131, 143, 145, 154, 159, 163, 168, 181, 197, 208, 232, 238, 241, 246, 249, 255, 256, 259, 263, 285, 286, 301, 314, 326, 329, 331, 332, 342, 354, 358, 359, 368, 379, 381, 385, 389, 392, 398, 402, 412, 414, 426, 429, 430, 441, 444, 447, 459, 474, 484, 487, 495, 496, 498, 511, 524, 525, 540, 542]
Qwen3_0_6B_ja_gsd_grct_ja_gsd_grct root_logits
[18, 20, 43, 46, 52, 79, 80, 87, 111, 112, 113, 114, 115, 118, 123, 124, 125, 131, 143, 145, 154, 159, 163, 168, 181, 197, 201, 208, 232, 238, 241, 246, 249, 255, 256, 259, 263, 285, 286, 301, 314, 321, 326, 329, 331, 332, 342, 354, 358, 359, 368, 379, 381, 385, 389, 398, 402, 404, 412, 414, 429, 430, 441, 444, 447, 474, 484, 487, 495, 496, 498, 524, 525, 540, 542]
Qwen3_0_6B_ru_syntagrus_grct_ru_syntagrus original_logits
[24, 89, 110, 151, 169, 176, 225, 229, 240, 274, 276, 301, 336, 394, 426, 431, 452, 475, 489, 558, 575, 579, 710, 721, 729, 760, 761, 775, 784, 800, 823, 833, 835, 849, 850, 871, 876, 910, 936, 956, 966, 986, 1067, 1126, 1142, 1179, 1205, 1210, 1211, 1215, 1236, 1241, 1330, 1435, 1470, 1512, 1536, 1556, 1566, 1579, 1610, 1617, 1622, 1646, 1694, 1702, 1703, 1724, 1751, 1766, 1783, 1830, 1848, 1899, 1903, 1913, 1922, 2034, 2052, 2076, 2083, 2145, 2194, 2208, 2214, 2224, 2229, 2252, 2276, 2301, 2308, 2310, 2311, 2335, 2340, 2341, 2353, 2356, 2381, 2382, 2415, 2448, 2482, 2486, 2509, 2510, 2518, 2525, 2551, 2569, 2592, 2593, 2594, 2605, 2617, 2621, 2650, 2672, 2680, 2683, 2685, 2738, 2766, 2768, 2806, 2813, 2827, 2833, 2854, 2863, 2880, 2881, 2893, 2897, 2910, 2919, 2930, 2941, 2957, 2982, 2987, 2993, 3019, 3023, 3050, 3056, 3068, 3089, 3096, 3097, 3113, 3115, 3135, 3160, 3175, 3204, 3246, 3250, 3332, 3334, 3348, 3384, 3397, 3410, 3412, 3456, 3492, 3493, 3497, 3521, 3558, 3590, 3594, 3611, 3631, 3670, 3681, 3682, 3738, 3830, 3833, 3854, 3879, 3900, 3902, 3920, 3948, 3950, 3965, 3992, 4018, 4049, 4093, 4103, 4110, 4113, 4119, 4137, 4142, 4150, 4181, 4182, 4189, 4208, 4209, 4214, 4229, 4255, 4268, 4315, 4368, 4369, 4374, 4381, 4398, 4402, 4403, 4406, 4410, 4417, 4439, 4451, 4453, 4457, 4458, 4475, 4476, 4480, 4504, 4516, 4524, 4539, 4542, 4566, 4596, 4646, 4663, 4666, 4678, 4684, 4685, 4710, 4711, 4729, 4732, 4737, 4739, 4741, 4765, 4792, 4815, 4816, 4826, 4868, 4886, 4897, 4929, 4930, 4939, 4944, 4946, 4954, 4960, 4962, 4967, 4975, 4983, 4989, 4991, 4992, 5000, 5012, 5015, 5020, 5023, 5038, 5168, 5232, 5265, 5266, 5278, 5292, 5294, 5302, 5346, 5383, 5419, 5461, 5463, 5477, 5478, 5505, 5522, 5532, 5562, 5612, 5626, 5633, 5640, 5646, 5661, 5662, 5668, 5753, 5757, 5775, 5806, 5822, 5824, 5830, 5837, 5852, 6010, 6011, 6026, 6044, 6055, 6081, 6095, 6112, 6133, 6206, 6249, 6252, 6257, 6268, 6274, 6329, 6345, 6348, 6399, 6418, 6487, 6489, 6538, 6593, 6625, 6717, 6755, 6761, 6766, 6781, 6811, 6816, 6840, 6842, 6843, 6858, 6866, 6879, 6911, 6913, 6924, 6925, 6934, 6937, 7012, 7013, 7020, 7025, 7030, 7036, 7039, 7041, 7046, 7155, 7233, 7243, 7261, 7364, 7377, 7380, 7398, 7402, 7406, 7410, 7412, 7413, 7414, 7418, 7428, 7431, 7434, 7435, 7436, 7439, 7441, 7447, 7455, 7457, 7468, 7479, 7491, 7500, 7501, 7504, 7510, 7514, 7515, 7516, 7519, 7523, 7524, 7539, 7550, 7572, 7578, 7587, 7596, 7636, 7638, 7642, 7649, 7651, 7661, 7666, 7672, 7677, 7679, 7680, 7689, 7700, 7705, 7716, 7721, 7725, 7736, 7758, 7779, 7812, 7843, 7897, 7926, 7968, 7972, 8010, 8111, 8117, 8135, 8170, 8241, 8269, 8274, 8290, 8296, 8316, 8319, 8374, 8416, 8494, 8503, 8523, 8544, 8569, 8581, 8651, 8654, 8764]
Qwen3_4B_ja_gsd_grct_ja_gsd_grct original_logits
[7, 38, 46, 67, 86, 93, 102, 106, 113, 117, 125, 145, 152, 161, 167, 182, 201, 211, 219, 221, 222, 224, 226, 231, 239, 240, 244, 257, 262, 296, 298, 303, 314, 321, 328, 350, 385, 386, 392, 396, 415, 434, 441, 442, 444, 447, 470, 472, 487, 493, 494, 496, 499, 505, 517, 524, 530]
Qwen3_4B_ja_gsd_grct_ja_gsd_grct main_logits
[6, 10, 17, 33, 35, 38, 39, 46, 59, 75, 78, 79, 81, 87, 90, 99, 100, 101, 102, 105, 106, 107, 108, 109, 113, 114, 118, 123, 124, 127, 129, 130, 131, 135, 140, 145, 150, 151, 152, 153, 156, 160, 161, 163, 164, 165, 168, 169, 174, 176, 181, 188, 190, 194, 203, 205, 208, 211, 217, 218, 221, 224, 225, 229, 230, 231, 232, 234, 239, 240, 241, 242, 243, 246, 251, 253, 256, 259, 260, 261, 262, 263, 264, 270, 276, 279, 285, 286, 290, 295, 297, 298, 299, 305, 310, 312, 315, 316, 317, 318, 319, 321, 325, 327, 328, 332, 338, 341, 342, 348, 350, 353, 354, 359, 364, 365, 367, 368, 370, 373, 374, 377, 378, 379, 380, 382, 384, 385, 391, 393, 397, 401, 407, 410, 415, 417, 419, 421, 425, 426, 427, 428, 429, 434, 438, 439, 441, 446, 447, 448, 449, 451, 453, 454, 455, 457, 459, 460, 462, 464, 466, 467, 468, 471, 472, 474, 475, 476, 477, 478, 479, 481, 482, 484, 489, 494, 495, 505, 506, 509, 510, 512, 513, 521, 524, 525, 526, 528, 531, 536, 539, 540, 541, 542]
Qwen3_4B_ja_gsd_grct_ja_gsd_grct root_logits